micronaut:
  application:
    name: noted
  session:
    http:
      cookie: true
      header: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
    db-type: postgres
flyway:
  datasources:
    default:
      enabled: true
